[package]
name = "hug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "2.0.1"
regex = "1"
lazy_static = "1.4.0"
once_cell = "1.17.1"
